apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-deploy-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
